- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'testdemopoo'
    backendAzureRmResourceGroupName: 'testingdemo'
    backendAzureRmStorageAccountName: 'storagepoo'
    backendAzureRmContainerName: 'backend'
    backendAzureRmKey: 'tf/terraform.tfstate'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'testdemopoo'
    command: 'validate'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'testdemopoo'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    environmentServiceNameAzureRM: 'testdemopoo'