- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Visual Studio Enterprise Subscription(729e44c4-c672-4524-ae6f-facbd854d997)'
    backendAzureRmResourceGroupName: 'testingdemo'
    backendAzureRmStorageAccountName: 'storagepoo'
    backendAzureRmContainerName: 'backend'
    backendAzureRmKey: 'tf/terraform.tfstate'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription(729e44c4-c672-4524-ae6f-facbd854d997)'